// Code generated by tools/wiregen; DO NOT EDIT.
// wireconv_gen.go — merge ↔ wire 镜像的双向转换，由 `go run ./tools/wiregen`
// 从两侧 struct 形状（json tag 配对）生成。手写面只剩非机械 helper（若有，
// 见同目录 wireconv.go）。生成规则即纪律：wire 有域无＝镜像谎言（生成期
// 报错）；域有 wire 无＝刻意不进协议（文件尾清单成文）。改字段流程：
// 域＋wire 镜像＋fixture 三处手写，跑一次 wiregen，其余全生成。

package merge

import "github.com/WWestC/Niuma_Studio/wire"

// Wire projects the merge onto its protocol mirror.
func (m *Merge) Wire() *wire.Merge {
	if m == nil {
		return nil
	}
	out := wire.Merge{
		ID:          m.ID,
		ProjectKey:  m.ProjectKey,
		Branch:      m.Branch,
		Into:        m.Into,
		Req:         m.Req,
		Tasks:       m.Tasks,
		Commits:     m.Commits,
		Files:       m.Files,
		Additions:   m.Additions,
		Deletions:   m.Deletions,
		SubmittedBy: m.SubmittedBy,
		SubmittedTS: m.SubmittedTS,
	}
	return &out
}

// MergeFromWire is Wire's inverse (nil-safe: a nil frame payload stays nil —
// "absent" and "empty" are different wire states).
func MergeFromWire(w *wire.Merge) *Merge {
	if w == nil {
		return nil
	}
	out := Merge{
		ID:          w.ID,
		ProjectKey:  w.ProjectKey,
		Branch:      w.Branch,
		Into:        w.Into,
		Req:         w.Req,
		Tasks:       w.Tasks,
		Commits:     w.Commits,
		Files:       w.Files,
		Additions:   w.Additions,
		Deletions:   w.Deletions,
		SubmittedBy: w.SubmittedBy,
		SubmittedTS: w.SubmittedTS,
	}
	return &out
}
