// Code generated by tools/wiregen; DO NOT EDIT.
// wireconv_gen.go — tasks ↔ wire 镜像的双向转换，由 `go run ./tools/wiregen`
// 从两侧 struct 形状（json tag 配对）生成。手写面只剩非机械 helper（若有，
// 见同目录 wireconv.go）。生成规则即纪律：wire 有域无＝镜像谎言（生成期
// 报错）；域有 wire 无＝刻意不进协议（文件尾清单成文）。改字段流程：
// 域＋wire 镜像＋fixture 三处手写，跑一次 wiregen，其余全生成。

package tasks

import "github.com/WWestC/Niuma_Studio/wire"

// Wire projects the task onto its protocol mirror.
func (t *Task) Wire() *wire.Task {
	if t == nil {
		return nil
	}
	out := wire.Task{
		ID:          t.ID,
		Title:       t.Title,
		Desc:        t.Desc,
		Assignee:    t.Assignee,
		Status:      t.Status,
		Progress:    t.Progress,
		CreatedBy:   t.CreatedBy,
		CreatedTS:   t.CreatedTS,
		UpdatedTS:   t.UpdatedTS,
		ProjectKey:  t.ProjectKey,
		Parent:      t.Parent,
		Req:         t.Req,
		Version:     t.Version,
		PlanID:      t.PlanID,
		StartTS:     t.StartTS,
		EndTS:       t.EndTS,
		Deps:        t.Deps,
		Milestone:   t.Milestone,
		ProgressPct: t.ProgressPct,
		Priority:    t.Priority,
		DoingTS:     t.DoingTS,
		DoneTS:      t.DoneTS,
	}
	if len(t.Log) > 0 {
		out.Log = make([]wire.LogEntry, len(t.Log))
		for i, e := range t.Log {
			out.Log[i] = wire.LogEntry{
				TS:   e.TS,
				By:   e.By,
				Note: e.Note,
			}
		}
	}
	if t.Pending != nil {
		out.Pending = t.Pending.Wire()
	}
	return &out
}

// TaskFromWire is Wire's inverse (nil-safe: a nil frame payload stays nil —
// "absent" and "empty" are different wire states).
func TaskFromWire(w *wire.Task) *Task {
	if w == nil {
		return nil
	}
	out := Task{
		ID:          w.ID,
		Title:       w.Title,
		Desc:        w.Desc,
		Assignee:    w.Assignee,
		Status:      w.Status,
		Progress:    w.Progress,
		CreatedBy:   w.CreatedBy,
		CreatedTS:   w.CreatedTS,
		UpdatedTS:   w.UpdatedTS,
		ProjectKey:  w.ProjectKey,
		Parent:      w.Parent,
		Req:         w.Req,
		Version:     w.Version,
		PlanID:      w.PlanID,
		StartTS:     w.StartTS,
		EndTS:       w.EndTS,
		Deps:        w.Deps,
		Milestone:   w.Milestone,
		ProgressPct: w.ProgressPct,
		Priority:    w.Priority,
		DoingTS:     w.DoingTS,
		DoneTS:      w.DoneTS,
	}
	if len(w.Log) > 0 {
		out.Log = make([]LogEntry, len(w.Log))
		for i, e := range w.Log {
			out.Log[i] = LogEntry{
				TS:   e.TS,
				By:   e.By,
				Note: e.Note,
			}
		}
	}
	out.Pending = ProposalFromWire(w.Pending)
	return &out
}

// Wire projects the patch onto its protocol mirror.
func (p Patch) Wire() wire.Patch {
	return wire.Patch{
		Status:    p.Status,
		Progress:  p.Progress,
		Note:      p.Note,
		Assignee:  p.Assignee,
		Project:   p.Project,
		Version:   p.Version,
		Start:     p.Start,
		End:       p.End,
		Deps:      p.Deps,
		Milestone: p.Milestone,
		Pct:       p.Pct,
		Priority:  p.Priority,
	}
}

// PatchFromWire is Wire's inverse (nil-safe: a nil frame payload stays nil —
// "absent" and "empty" are different wire states).
func PatchFromWire(w *wire.Patch) Patch {
	if w == nil {
		return Patch{}
	}
	return Patch{
		Status:    w.Status,
		Progress:  w.Progress,
		Note:      w.Note,
		Assignee:  w.Assignee,
		Project:   w.Project,
		Version:   w.Version,
		Start:     w.Start,
		End:       w.End,
		Deps:      w.Deps,
		Milestone: w.Milestone,
		Pct:       w.Pct,
		Priority:  w.Priority,
	}
}

// Wire projects the proposal onto its protocol mirror.
func (p *Proposal) Wire() *wire.Proposal {
	if p == nil {
		return nil
	}
	out := wire.Proposal{
		By:    p.By,
		Patch: p.Patch.Wire(),
		Need:  p.Need,
		Got:   p.Got,
		Kind:  p.Kind,
		TS:    p.TS,
	}
	return &out
}

// ProposalFromWire is Wire's inverse (nil-safe: a nil frame payload stays nil —
// "absent" and "empty" are different wire states).
func ProposalFromWire(w *wire.Proposal) *Proposal {
	if w == nil {
		return nil
	}
	out := Proposal{
		By:    w.By,
		Patch: PatchFromWire(&w.Patch),
		Need:  w.Need,
		Got:   w.Got,
		Kind:  w.Kind,
		TS:    w.TS,
	}
	return &out
}
