// Code generated by tools/wiregen; DO NOT EDIT.
// wireconv_gen.go — meeting ↔ wire 镜像的双向转换，由 `go run ./tools/wiregen`
// 从两侧 struct 形状（json tag 配对）生成。手写面只剩非机械 helper（若有，
// 见同目录 wireconv.go）。生成规则即纪律：wire 有域无＝镜像谎言（生成期
// 报错）；域有 wire 无＝刻意不进协议（文件尾清单成文）。改字段流程：
// 域＋wire 镜像＋fixture 三处手写，跑一次 wiregen，其余全生成。

package meeting

import "github.com/WWestC/Niuma_Studio/wire"

// Wire projects the meeting onto its protocol mirror.
func (m *Meeting) Wire() *wire.Meeting {
	if m == nil {
		return nil
	}
	out := wire.Meeting{
		ID:           m.ID,
		ProjectKey:   m.ProjectKey,
		ReqID:        m.ReqID,
		ReqTitle:     m.ReqTitle,
		Chair:        m.Chair,
		Participants: m.Participants,
		Status:       m.Status,
		Phase:        m.Phase,
		Opening:      m.Opening,
		Conclusion:   m.Conclusion,
		StartTS:      m.StartTS,
		EndTS:        m.EndTS,
	}
	if len(m.Transcript) > 0 {
		out.Transcript = make([]wire.Line, len(m.Transcript))
		for i, e := range m.Transcript {
			out.Transcript[i] = wire.Line{
				TS:   e.TS,
				By:   e.By,
				Text: e.Text,
			}
		}
	}
	return &out
}

// MeetingFromWire is Wire's inverse (nil-safe: a nil frame payload stays nil —
// "absent" and "empty" are different wire states).
func MeetingFromWire(w *wire.Meeting) *Meeting {
	if w == nil {
		return nil
	}
	out := Meeting{
		ID:           w.ID,
		ProjectKey:   w.ProjectKey,
		ReqID:        w.ReqID,
		ReqTitle:     w.ReqTitle,
		Chair:        w.Chair,
		Participants: w.Participants,
		Status:       w.Status,
		Phase:        w.Phase,
		Opening:      w.Opening,
		Conclusion:   w.Conclusion,
		StartTS:      w.StartTS,
		EndTS:        w.EndTS,
	}
	if len(w.Transcript) > 0 {
		out.Transcript = make([]Line, len(w.Transcript))
		for i, e := range w.Transcript {
			out.Transcript[i] = Line{
				TS:   e.TS,
				By:   e.By,
				Text: e.Text,
			}
		}
	}
	return &out
}
