// Code generated by tools/wiregen; DO NOT EDIT.
// wireconv_gen.go — plan ↔ wire 镜像的双向转换，由 `go run ./tools/wiregen`
// 从两侧 struct 形状（json tag 配对）生成。手写面只剩非机械 helper（若有，
// 见同目录 wireconv.go）。生成规则即纪律：wire 有域无＝镜像谎言（生成期
// 报错）；域有 wire 无＝刻意不进协议（文件尾清单成文）。改字段流程：
// 域＋wire 镜像＋fixture 三处手写，跑一次 wiregen，其余全生成。

package plan

import "github.com/WWestC/Niuma_Studio/wire"

// Wire projects the plan onto its protocol mirror.
func (p *Plan) Wire() *wire.Plan {
	if p == nil {
		return nil
	}
	out := wire.Plan{
		ID:          p.ID,
		Req:         p.Req,
		Title:       p.Title,
		Need:        p.Need,
		ProjectKey:  p.ProjectKey,
		Version:     p.Version,
		SubmittedBy: p.SubmittedBy,
		SubmittedTS: p.SubmittedTS,
	}
	if len(p.Tasks) > 0 {
		out.Tasks = make([]wire.PlanTask, len(p.Tasks))
		for i, e := range p.Tasks {
			out.Tasks[i] = wire.PlanTask{
				Title:     e.Title,
				Desc:      e.Desc,
				Assignee:  e.Assignee,
				StartTS:   e.StartTS,
				EndTS:     e.EndTS,
				Deps:      e.Deps,
				Milestone: e.Milestone,
			}
		}
	}
	return &out
}

// PlanFromWire is Wire's inverse (nil-safe: a nil frame payload stays nil —
// "absent" and "empty" are different wire states).
func PlanFromWire(w *wire.Plan) *Plan {
	if w == nil {
		return nil
	}
	out := Plan{
		ID:          w.ID,
		Req:         w.Req,
		Title:       w.Title,
		Need:        w.Need,
		ProjectKey:  w.ProjectKey,
		Version:     w.Version,
		SubmittedBy: w.SubmittedBy,
		SubmittedTS: w.SubmittedTS,
	}
	if len(w.Tasks) > 0 {
		out.Tasks = make([]PlanTask, len(w.Tasks))
		for i, e := range w.Tasks {
			out.Tasks[i] = PlanTask{
				Title:     e.Title,
				Desc:      e.Desc,
				Assignee:  e.Assignee,
				StartTS:   e.StartTS,
				EndTS:     e.EndTS,
				Deps:      e.Deps,
				Milestone: e.Milestone,
			}
		}
	}
	return &out
}
