// Code generated by tools/wiregen; DO NOT EDIT.
// wireconv_gen.go — requirements ↔ wire 镜像的双向转换，由 `go run ./tools/wiregen`
// 从两侧 struct 形状（json tag 配对）生成。手写面只剩非机械 helper（若有，
// 见同目录 wireconv.go）。生成规则即纪律：wire 有域无＝镜像谎言（生成期
// 报错）；域有 wire 无＝刻意不进协议（文件尾清单成文）。改字段流程：
// 域＋wire 镜像＋fixture 三处手写，跑一次 wiregen，其余全生成。

package requirements

import "github.com/WWestC/Niuma_Studio/wire"

// Wire projects the req onto its protocol mirror.
func (r *Req) Wire() *wire.Req {
	if r == nil {
		return nil
	}
	out := wire.Req{
		ID:          r.ID,
		ProjectKey:  r.ProjectKey,
		Title:       r.Title,
		Body:        r.Body,
		Status:      r.Status,
		CreatedBy:   r.CreatedBy,
		CreatedTS:   r.CreatedTS,
		ParkNote:    r.ParkNote,
		ParkTS:      r.ParkTS,
		ReviewAfter: r.ReviewAfter,
		ClosedTS:    r.ClosedTS,
	}
	return &out
}

// ReqFromWire is Wire's inverse (nil-safe: a nil frame payload stays nil —
// "absent" and "empty" are different wire states).
func ReqFromWire(w *wire.Req) *Req {
	if w == nil {
		return nil
	}
	out := Req{
		ID:          w.ID,
		ProjectKey:  w.ProjectKey,
		Title:       w.Title,
		Body:        w.Body,
		Status:      w.Status,
		CreatedBy:   w.CreatedBy,
		CreatedTS:   w.CreatedTS,
		ParkNote:    w.ParkNote,
		ParkTS:      w.ParkTS,
		ReviewAfter: w.ReviewAfter,
		ClosedTS:    w.ClosedTS,
	}
	return &out
}
